[package]
name = "attacca-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Attacca. Aplicación de escritorio conforme a STAVE 2.0."

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
attacca-core = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { workspace = true }
serde_json = { workspace = true }

[features]
# Tauri necesita esta característica para la compilación de producción.
custom-protocol = ["tauri/custom-protocol"]
